extends GdUnitTestSuite

## Hero surface quality (REQ-040): the baked maps, the material that wears
## them, and the polygon ceiling the whole dressed scene must stay under.
##
## The maps themselves are generated by tools/blender/bake_hero_maps.py and
## proven on the python side (reproducibility, geometry preservation); this
## suite proves the GODOT half — that what shipped actually reaches the
## renderer: the mesh carries the UVs the maps need, the client material
## carries the maps, and their sizes sit inside the Asset Contract's bounds.

const SKIN_MATERIAL := "res://core/rendering/materials/axolotl_skin.tres"
const HERO := "res://assets/character/axolotl/axolotl.glb"

## The character category's documented texture bounds (contracts/
## asset_contract.v1.json): 64..2048 on a side.
const TEXTURE_MIN := 64
const TEXTURE_MAX := 2048

## The whole-scene ceiling (REQ-040 AC-6). Far below "desktop struggles":
## the point is that regenerating a kit or dressing a bed cannot silently
## triple the scene, because this number is asserted rather than hoped.
const SCENE_TRIANGLE_BUDGET := 150000


func test_req_040_the_skin_material_carries_both_baked_maps() -> void:
	var material: StandardMaterial3D = load(SKIN_MATERIAL)
	assert_object(material).is_not_null()

	assert_object(material.albedo_texture).override_failure_message(
		"the detail map must ride the albedo slot, multiplied over the "
		+ "vertex colour").is_not_null()
	assert_bool(material.normal_enabled).override_failure_message(
		"the normal map does nothing with normal mapping disabled").is_true()
	assert_object(material.normal_texture).is_not_null()

	# The palette must keep living in the model's vertex colours: a detail
	# map that REPLACES the albedo instead of shading it would freeze the
	# palette into the bake.
	assert_bool(material.vertex_color_use_as_albedo).override_failure_message(
		"the detail map multiplies over vertex colour; it must not replace it"
	).is_true()


func test_req_040_the_baked_maps_sit_inside_the_contract_bounds() -> void:
	var material: StandardMaterial3D = load(SKIN_MATERIAL)
	for texture: Texture2D in [material.albedo_texture, material.normal_texture]:
		assert_bool(texture.get_width() >= TEXTURE_MIN
			and texture.get_width() <= TEXTURE_MAX
			and texture.get_height() >= TEXTURE_MIN
			and texture.get_height() <= TEXTURE_MAX).override_failure_message(
			"a character texture must sit inside the contract's %dx%d..%dx%d"
			% [TEXTURE_MIN, TEXTURE_MIN, TEXTURE_MAX, TEXTURE_MAX]).is_true()


func test_req_040_every_shipped_hero_surface_carries_uvs_for_its_maps() -> void:
	# A material full of textures over a mesh with no UV layout renders as one
	# texel smeared everywhere — silently. The unwrap has to ship IN the glb,
	# and this is the assertion that keeps it there.
	#
	# Held over EVERY surface rather than over the one named `axolotl_skin`.
	# That name is written by the in-repo generator, and the shipped hero is
	# now an externally authored single surface, so a lookup by name found
	# nothing and the test passed by measuring an empty set. What matters is
	# that no surface reaching the renderer lacks the layout its maps need,
	# which is a property of the mesh rather than of what it is called.
	var hero := (load(HERO) as PackedScene).instantiate()
	var surfaces := 0
	for node: Node in hero.find_children("*", "MeshInstance3D", true, false):
		var mesh := (node as MeshInstance3D).mesh
		if mesh == null:
			continue
		for surface: int in mesh.get_surface_count():
			surfaces += 1
			var arrays: Array = mesh.surface_get_arrays(surface)
			assert_bool(arrays[Mesh.ARRAY_TEX_UV] != null
				).override_failure_message(
				("%s surface %d ships without a UV layout; anything textured "
				+ "over it renders as one smeared texel")
				% [node.name, surface]).is_true()
	hero.free()
	assert_int(surfaces).override_failure_message(
		"the shipped hero has no surfaces at all").is_greater(0)


func test_req_040_the_dressed_valley_stays_inside_the_triangle_budget() -> void:
	# Counted over the instanced scene rather than read from a doc, so a
	# regenerated kit or a heavier dressing bed fails HERE, with a number,
	# before anyone's desktop finds out.
	var world := (load("res://worlds/coral_cove/world.tscn")
		as PackedScene).instantiate()
	var total := _count_triangles(world)
	world.free()

	var hero := (load(HERO) as PackedScene).instantiate()
	total += _count_triangles(hero)
	hero.free()

	assert_bool(total > 0).is_true()
	assert_bool(total <= SCENE_TRIANGLE_BUDGET).override_failure_message(
		"the dressed valley plus the hero is %d triangles against a %d budget"
		% [total, SCENE_TRIANGLE_BUDGET]).is_true()


func _count_triangles(scene: Node) -> int:
	var total := 0
	for node: Node in scene.find_children("*", "MeshInstance3D", true, false):
		total += _mesh_triangles((node as MeshInstance3D).mesh)

	# SCATTERED DRESSING COUNTS TOO, and counting it needs its own branch: a
	# ScatterField draws through a MultiMeshInstance3D, which is not a
	# MeshInstance3D, so the loop above walks straight past it. When the
	# valley's 183 props became 9 fields this counter silently stopped seeing
	# 43,320 triangles — the budget assertion would have kept passing while
	# measuring almost nothing, which is the most dangerous way for a gate to
	# break. One mesh times its instance count is the real cost.
	# Visual shells are geometry too. They are cheap — tens of triangles each —
	# but a counter that cannot see them would let a shell pass that generated
	# hundreds, and the whole point of the budget is that it notices.
	for node: Node in scene.find_children("*", "Node3D", true, false):
		var shell := node as TerrainShell
		if shell != null:
			total += shell.shell_triangles()

	for node: Node in scene.find_children("*", "Node3D", true, false):
		var field := node as ScatterField
		if field == null:
			continue
		# Read what the field DECLARES rather than what it has built: this
		# suite instantiates the world without adding it to a tree, so no
		# _ready has run and there is no MultiMesh to interrogate yet.
		total += _mesh_triangles(field.get_source_mesh()) * field.instance_count()
	return total


func _mesh_triangles(mesh: Mesh) -> int:
	if mesh == null:
		return 0
	var total := 0
	for surface: int in mesh.get_surface_count():
		var arrays: Array = mesh.surface_get_arrays(surface)
		var indices: Variant = arrays[Mesh.ARRAY_INDEX]
		if indices != null:
			total += (indices as PackedInt32Array).size() / 3
		elif arrays[Mesh.ARRAY_VERTEX] != null:
			total += (arrays[Mesh.ARRAY_VERTEX] as PackedVector3Array).size() / 3
	return total
