"""Fit a skeleton to an EXTERNAL hero mesh — RUNS INSIDE BLENDER (bpy):

    blender --background --python-exit-code 1 \
        --python tools/blender/fit_hero_rig.py -- \
        --input reference/hero/pink_axolotl_2_reduced.glb \
        --reference assets/character/axolotl/axolotl.glb \
        [--output /tmp/hero_normalised.glb]

WHY A FITTER EXISTS AT ALL. tools/blender/rig_model.py carries a hand-authored
BONES table: twelve bones whose coordinates were measured off the GENERATED
axolotl, one number at a time. That table is not portable, and the Meshy hero
proved it. Normalised by body length the two creatures are not the same
animal:

    height / length     generated 0.487     Meshy 0.256
    width  / length     generated 0.406     Meshy 0.435

The generated hero is a chunky upright toy; the Meshy export is a flat,
sprawling real axolotl, half as tall for its length, narrowing to a snout
where the toy stays wide to the tip. The hand-authored gill bones reach
z = 1.27 on a model 2.28 tall — on the Meshy hero at the same body length the
whole creature is 1.20 tall, so those bones would float in the air above it,
and automatic weights against them would produce nonsense.

WHAT IS KEPT AND WHAT IS FITTED, and the split is the whole design:

  * THE BONE NAMES ARE KEPT, EXACTLY. All six animation clips in
    rig_model.py — idle, waddle, swim, hop, fall, hurt — are generated by
    keying rotation_euler on bones BY NAME (tail_1..3, leg_fl/fr/bl/br,
    gill_l/r, head, spine, root). They never reference a bone POSITION. So a
    refitted table with the same names regenerates all six clips with no
    re-authoring whatsoever. That is why this is a fitter and not a rewrite.
  * THE LENGTHWISE DIVISION IS KEPT. Where the tail becomes the body and the
    body becomes the head is a fact about axolotls, not about one model, so
    the fitter reuses the reference table's Y stations after normalising both
    creatures to the same body length.
  * THE HEIGHTS ARE FITTED, because that is exactly what differs. Each spine,
    root, head and tail bone is placed on the mesh's own centreline: the
    vertical centre of the body's cross-section at that station, measured
    from geometry near the midline so flared gills and splayed legs cannot
    drag the spine off-centre.
  * THE LIMBS AND GILLS ARE FITTED FROM GEOMETRY, because proportional
    mapping is wrong for them specifically. Legs are found as the lateral
    mass BELOW the body centreline, split front/back and left/right; gills as
    the widest lateral protrusion in the head region. On the toy the gills
    sweep UP; on a real axolotl they sweep back and out, and no amount of
    rescaling turns one into the other.

NORMALISATION comes first and is not cosmetic. The mesh is flipped to put the
head at +Y (the Meshy export has it at -Y), scaled to the reference's body
length, and dropped so its lowest point sits on the FLOOR the caller names.

THE FLOOR IS AN ARGUMENT BECAUSE THE REFERENCE'S OWN IS A TRAP. Defaulting it
to the reference model's bounding-box minimum looks obviously right and buried
the first hero half a metre under the sand: the previous hero's bounding box
reached down to -1.0 in authoring space while its BODY sat at about -0.09, so
matching bounding boxes matched two different things. The number that matters
is where the collision capsule's bottom lands once the game scene has applied
its own scale and offset, and for core/controller/axolotl_body.tscn that is
-0.04. Measured in Godot, not derived on paper -- the hero was placed, its
world AABB read back, and the difference taken.
Doing that here rather than in the game scene means core/controller/
axolotl_body.tscn keeps its transform unchanged — the model arrives already
in the authoring frame the scene was built around, so the collision capsule,
the camera framing and every walk probe stay exactly as proven.

This writes NO armature and NO weights. It reports a table and, optionally,
the normalised mesh. Rigging is rig_model.py's job, and keeping the fit
separate is what lets the table be read and argued with before anything is
bound to it.
"""

from __future__ import annotations

import argparse
import json
import math
import sys

import bpy  # type: ignore  # only importable inside Blender
import numpy as np  # type: ignore

## Bones whose Y stations come from the reference table and whose Z is fitted
## to the target mesh's own centreline. Ordered parent-first.
SPINE_CHAIN = ("root", "spine", "head", "tail_1", "tail_2", "tail_3")

## How much of the half-width counts as "near the midline" when measuring the
## body's centreline. A third: wide enough to sit on real body mass at every
## station, narrow enough that a flared gill or a splayed foot never reaches.
MIDLINE_FRACTION = 0.33

## Stations sampled along the body when profiling its top-down silhouette.
## Two hundred over roughly five units is a sample every 2.3 mm of authoring
## space — finer than any feature being looked for, coarse enough to stay
## smooth on a decimated mesh.
SILHOUETTE_STATIONS = 200

## How far the left and right fit may disagree before the fit is rejected, as
## a fraction of body length.
##
## THIS IS A GATE, NOT A TOLERANCE. An axolotl is bilaterally symmetric, so a
## fitter that puts one gill at x=0.95 and its mirror at x=-0.50 has not found
## the gills — it has found one gill and some noise. That exact thing happened
## twice while this file was being written, and both times the numbers looked
## plausible in isolation and the rig would have deformed visibly wrong on one
## side only. Symmetry is the cheapest available check that the fit found real
## anatomy, so it is enforced rather than inspected.
SYMMETRY_TOLERANCE = 0.04


def mesh_points() -> np.ndarray:
    """Every vertex in the scene, in world space."""
    chunks = []
    for obj in bpy.data.objects:
        if obj.type != "MESH":
            continue
        mesh = obj.data
        raw = np.empty(len(mesh.vertices) * 3, dtype=np.float64)
        mesh.vertices.foreach_get("co", raw)
        raw = raw.reshape(-1, 3)
        matrix = np.array(obj.matrix_world.to_4x4(), dtype=np.float64)
        chunks.append(raw @ matrix[:3, :3].T + matrix[:3, 3])
    return np.vstack(chunks)


def load_points(path: str) -> np.ndarray:
    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.import_scene.gltf(filepath=path)
    return mesh_points()


def head_is_at_plus_y(points: np.ndarray) -> bool:
    """Which end is the head, decided by cross-section rather than by faith.

    An axolotl's head end carries the gills and is far wider than its tail,
    which tapers to a fin. Measuring that is one line and removes the single
    most likely silent error in this file — a model imported backwards, rigged
    backwards, and animated swimming tail-first.
    """
    span = points[:, 1]
    low, high = span.min(), span.max()
    reach = high - low
    front = points[span > high - 0.12 * reach]
    back = points[span < low + 0.12 * reach]
    return np.ptp(front[:, 0]) > np.ptp(back[:, 0])


def normalise(points: np.ndarray, reference: np.ndarray,
              floor: float | None = None) -> tuple:
    """Put the target in the reference's authoring frame.

    Returns the transformed points and the (flip, scale, offset) that did it,
    so the same transform can be replayed on the real mesh datablocks.
    """
    # THE BODY IS NOT AXIS-ALIGNED, and assuming it was invalidated every
    # measurement taken before this. The Meshy export's axolotl lies at a yaw
    # to the XY axes, so profiling "how far out does the body reach at this
    # station along Y" walked diagonally across the animal: over the back half
    # of the model one side of the midline held NO vertices at all, and every
    # left/right pair the fitter produced came out lopsided. The mesh was
    # fine; the frame was wrong.
    #
    # The long axis is the dominant eigenvector of the vertex cloud in plan
    # view, which for a creature four times longer than it is wide is not a
    # close call.
    moved = points.copy()
    centre = moved[:, :2].mean(axis=0)
    plan = moved[:, :2] - centre
    _values, vectors = np.linalg.eigh(np.cov(plan.T))
    longest = vectors[:, -1]
    yaw = math.atan2(longest[1], longest[0]) - 0.5 * math.pi
    cos, sin = math.cos(-yaw), math.sin(-yaw)
    moved[:, 0], moved[:, 1] = (cos * plan[:, 0] - sin * plan[:, 1],
                                sin * plan[:, 0] + cos * plan[:, 1])

    flip = not head_is_at_plus_y(moved)
    if flip:
        moved[:, 0] = -moved[:, 0]
        moved[:, 1] = -moved[:, 1]

    scale = np.ptp(reference[:, 1]) / np.ptp(moved[:, 1])
    moved *= scale

    # X centred, Y span aligned with the reference, and the lowest point on
    # the reference's ground plane — so the game scene's own transform, which
    # was built around the reference, keeps working untouched.
    offset = np.array([
        -0.5 * (moved[:, 0].min() + moved[:, 0].max()),
        reference[:, 1].min() - moved[:, 1].min(),
        (reference[:, 2].min() if floor is None else floor) - moved[:, 2].min(),
    ])
    return moved + offset, (flip, float(scale), offset.tolist(),
                            float(yaw), centre.tolist())


def centreline(points: np.ndarray, station: float, reach: float) -> float:
    """The vertical centre of the body at one point along its length."""
    half_width = MIDLINE_FRACTION * 0.5 * np.ptp(points[:, 0])
    slab = points[(np.abs(points[:, 1] - station) < reach)
                  & (np.abs(points[:, 0]) < half_width)]
    if len(slab) < 8:
        slab = points[np.abs(points[:, 1] - station) < reach * 2.0]
    if len(slab) == 0:
        return 0.0
    return float(0.5 * (slab[:, 2].min() + slab[:, 2].max()))


def fit_spine(points: np.ndarray, table: list) -> dict:
    """Reference Y stations, heights taken from the target's own centreline."""
    reach = 0.04 * np.ptp(points[:, 1])
    fitted = {}
    for name, parent, head, tail in table:
        if name not in SPINE_CHAIN:
            continue
        fitted[name] = (
            parent,
            (0.0, head[1], centreline(points, head[1], reach)),
            (0.0, tail[1], centreline(points, tail[1], reach)),
        )
    return fitted


def leg_band(table: list) -> tuple:
    """The stretch of body that can hold a leg: behind the head, before the tail.

    Bounded from the reference table rather than guessed. Without this bound
    the search finds the tail fin (which also hangs below the body line) and
    the gills (which are the widest lateral mass on the animal) and calls them
    legs — the first fit put a front leg at y=0.75, inside the gills, and a
    back leg at y=-2.18, halfway down the tail.
    """
    by_name = {row[0]: row for row in table}
    rear = by_name["tail_1"][2][1]
    front = by_name["head"][2][1]
    return float(rear), float(front)


def silhouette(points: np.ndarray, side: float, low: float,
               high: float, lower_only: bool = False) -> tuple:
    """One side's top-down outline: how far out the body reaches, per station.

    THE TOP-DOWN OUTLINE IS WHERE LIMBS ARE UNAMBIGUOUS. Fitting them by
    height failed twice, and for the same reason both times: on a sprawling
    animal the entire belly is low, so "mass below the body" is the whole
    underside and its lateral median sits near the midline — which is how a
    front foot came out at x=0.09 on a creature a metre wide. Seen from above
    there is no such ambiguity. The torso is a smooth taper and each limb is a
    bump standing out of it, so a leg is a local maximum of this curve and
    nothing else is.
    """
    flank = points[points[:, 0] * side > 0]
    # EXCLUDED, not clipped. Clipping folds everything beyond the band into
    # its end bins, which is not a subtle error: with the band ending at the
    # shoulders, every gill vertex piled into the last bin and the front-leg
    # search returned the gill tip — leg_fl and gill_l came back at the same
    # point, 0.96 out and 0.74 forward.
    flank = flank[(flank[:, 1] >= low) & (flank[:, 1] <= high)]
    if lower_only and len(flank):
        # Legs are the widest thing in the BOTTOM of the cross-section. The
        # torso is also wide at the shoulders, and wide at mid-height, so a
        # profile over the full section picks the shoulder and calls it a
        # leg. Restricting to the lower two fifths separates them, because a
        # sprawling axolotl's feet are the only mass down there that reaches
        # out sideways.
        floor = flank[:, 2].min()
        span = np.ptp(flank[:, 2])
        flank = flank[flank[:, 2] <= floor + 0.40 * span]
    edges = np.linspace(low, high, SILHOUETTE_STATIONS + 1)
    centres = 0.5 * (edges[:-1] + edges[1:])
    reach = np.zeros(SILHOUETTE_STATIONS)
    if len(flank) == 0:
        return centres, reach
    index = np.clip(np.digitize(flank[:, 1], edges) - 1, 0,
                    SILHOUETTE_STATIONS - 1)
    np.maximum.at(reach, index, np.abs(flank[:, 0]))
    return centres, reach


def widest_in(points: np.ndarray, side: float, low: float,
              high: float, lower_only: bool = False) -> tuple:
    """The outermost point of one side between two stations, as a 3-vector.

    Taken as a median over the outer decile rather than the single furthest
    vertex: on a webbed foot that vertex is one toe tip and on a gill it is
    one filament, both of which wander and neither of which is the limb.
    """
    band = points[(points[:, 1] >= low) & (points[:, 1] <= high)]
    flank = band[band[:, 0] * side > 0]
    if lower_only and len(flank):
        # The station was chosen from the lower silhouette; the point must
        # come from there too. Without this the search returns the widest
        # vertex at that station at ANY height, which is the shoulder -- the
        # front feet came out at z=-0.21 while the rear feet, found the same
        # way but on a part of the body with no shoulder above them, sat
        # correctly at z=-0.97.
        floor = flank[:, 2].min()
        flank = flank[flank[:, 2] <= floor + 0.40 * np.ptp(flank[:, 2])]
    if len(flank) < 8:
        return None
    outer = flank[np.abs(flank[:, 0])
                  >= np.percentile(np.abs(flank[:, 0]), 90.0)]
    return (float(np.median(outer[:, 0])), float(np.median(outer[:, 1])),
            float(np.median(outer[:, 2])))


def fit_limbs(points: np.ndarray, table: list) -> dict:
    """Legs as the lateral peaks of the top-down outline, inside the leg band.

    Bounded lengthwise to the stretch that can hold a leg (behind the head,
    ahead of the tail) so the tail fin and the gills — the two other places
    the animal is wide — cannot be mistaken for limbs. Within that, each side
    contributes exactly two peaks, front and back, which is exactly the number
    of legs a side has.
    """
    rear, front = leg_band(table)
    middle = 0.5 * (rear + front)

    fitted = {}
    for name, parent, head, tail in table:
        if not name.startswith("leg_"):
            continue
        side = 1.0 if head[0] > 0 else -1.0
        forward = name.endswith("fl") or name.endswith("fr")
        low, high = (middle, front) if forward else (rear, middle)

        stations, reach = silhouette(points, side, low, high, lower_only=True)
        if not reach.any():
            fitted[name] = (parent, head, tail)
            continue
        peak = float(stations[int(np.argmax(reach))])
        width = 0.05 * np.ptp(points[:, 1])
        # Clamped to the band. Unclamped, a peak sitting on the band edge
        # opened a window that reached past the shoulders into the gills, and
        # the front leg was fitted to the gill tip.
        foot = widest_in(points, side, max(low, peak - width),
                         min(high, peak + width), lower_only=True)
        if foot is None:
            fitted[name] = (parent, head, tail)
            continue

        # The root sits where the limb leaves the body, on the belly line at
        # the same station; the tip sits at the foot.
        belly = centreline(points, foot[1], width)
        fitted[name] = (parent,
                        (side * 0.25 * abs(foot[0]), foot[1], belly), foot)
    return fitted


def fit_gills(points: np.ndarray, table: list) -> dict:
    """Gills as the lateral peak of the outline across the head bone's stretch.

    Fitted rather than rescaled from the reference because this is where the
    two creatures diverge most: the generated toy's gills sweep UP, and a real
    axolotl's sweep BACK and OUT. Rescaling one into the other points the bone
    out of the model.
    """
    by_name = {row[0]: row for row in table}
    neck = float(by_name["head"][2][1])
    snout = points[:, 1].max() - 0.04 * np.ptp(points[:, 1])

    fitted = {}
    for name, parent, head, tail in table:
        if not name.startswith("gill_"):
            continue
        side = 1.0 if head[0] > 0 else -1.0
        stations, reach = silhouette(points, side, neck, snout)
        if not reach.any():
            fitted[name] = (parent, head, tail)
            continue
        peak = float(stations[int(np.argmax(reach))])
        width = 0.05 * np.ptp(points[:, 1])
        tip = widest_in(points, side, max(neck, peak - width),
                        min(snout, peak + width))
        if tip is None:
            fitted[name] = (parent, head, tail)
            continue
        skull = centreline(points, tip[1], width)
        fitted[name] = (parent,
                        (side * 0.30 * abs(tip[0]), tip[1], skull), tip)
    return fitted


def mirror_pairs(fitted: dict) -> tuple:
    """Make each left/right pair an exact mirror, and say what it cost.

    WHY MIRROR RATHER THAN FIT BOTH SIDES. An axolotl is bilaterally
    symmetric. That is not something to be rediscovered per side from a
    decimated, AI-generated mesh whose two flanks carry different vertex
    densities (20,895 against 17,007 here) — it is a fact about the animal
    that the rig should assert. Fitting both sides independently means the
    rig is only as good as the WORSE side, and a limb bone that lands
    differently left and right deforms visibly wrong on one side only, which
    is precisely the defect that survives review and shows up in a cutscene.

    The side kept is the one that reaches further, because these features are
    protrusions: a side that under-reads has missed the limb and found the
    torso beside it, while a side cannot invent reach it does not have.

    The disagreement is not discarded. It is reported, because a genuinely
    lopsided mesh is worth knowing about even once the rig has been made
    symmetric over the top of it.
    """
    pairs = (("leg_fl", "leg_fr"), ("leg_bl", "leg_br"), ("gill_l", "gill_r"))
    disagreement = []
    for left, right in pairs:
        if left not in fitted or right not in fitted:
            continue
        keep, drop = (left, right) if abs(fitted[left][2][0]) >= \
            abs(fitted[right][2][0]) else (right, left)
        disagreement.append({
            "pair": "%s/%s" % (left, right),
            "kept": keep,
            "lateralDisagreement": round(
                abs(abs(fitted[left][2][0]) - abs(fitted[right][2][0])), 4),
            "lengthwiseDisagreement": round(
                abs(fitted[left][2][1] - fitted[right][2][1]), 4),
        })
        parent, root, tip = fitted[keep]
        sign = -1.0 if drop.endswith(("r", "_r")) or drop == "gill_r" else 1.0
        # The dropped side becomes the kept side reflected through x = 0.
        fitted[drop] = (fitted[drop][0],
                        (-root[0], root[1], root[2]),
                        (-tip[0], tip[1], tip[2]))
    return fitted, disagreement


def check_protrusions(fitted: dict, points: np.ndarray) -> list:
    """Every limb and gill tip must be OUTSIDE the torso at its own station.

    This replaces the symmetry gate, which mirroring made vacuous. It asks
    the question that still has an answer: did the fit find a protrusion, or
    did it find the side of the body? A bone whose tip sits inside the torso
    is not a limb, however symmetric it is — and automatic weights bound to
    it would drag the flank around instead of the leg.
    """
    reach = 0.04 * np.ptp(points[:, 1])
    half_width = MIDLINE_FRACTION * 0.5 * np.ptp(points[:, 0])
    broken = []
    for name, (_parent, _root, tip) in sorted(fitted.items()):
        if not (name.startswith("leg_") or name.startswith("gill_")):
            continue
        slab = points[np.abs(points[:, 1] - tip[1]) < reach]
        torso = slab[np.abs(slab[:, 0]) < half_width]
        if len(torso) == 0:
            continue
        if abs(tip[0]) <= half_width:
            broken.append({
                "bone": name,
                "tipLateral": round(abs(tip[0]), 4),
                "torsoHalfWidth": round(float(half_width), 4),
                "why": "the tip sits inside the torso, so this bone is not "
                       "on a limb",
            })
    return broken


def check_symmetry(fitted: dict, length: float) -> list:
    """Left and right must mirror. Returns the pairs that do not.

    See SYMMETRY_TOLERANCE: this is the check that the fit found anatomy
    rather than noise, and it is the one that caught both earlier bad fits.
    """
    pairs = (("leg_fl", "leg_fr"), ("leg_bl", "leg_br"), ("gill_l", "gill_r"))
    limit = SYMMETRY_TOLERANCE * length
    broken = []
    for left, right in pairs:
        if left not in fitted or right not in fitted:
            continue
        lt, rt = fitted[left][2], fitted[right][2]
        lateral = abs(lt[0] + rt[0])
        along = abs(lt[1] - rt[1])
        if lateral > limit or along > limit:
            broken.append({
                "pair": "%s/%s" % (left, right),
                "lateralMismatch": round(lateral, 4),
                "lengthwiseMismatch": round(along, 4),
                "limit": round(limit, 4),
                "left": [round(v, 4) for v in lt],
                "right": [round(v, 4) for v in rt],
            })
    return broken


def reference_table() -> list:
    """rig_model.py's hand-authored table, read rather than duplicated."""
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, here)
    import rig_model  # type: ignore
    return rig_model.BONES


def parse_args(argv: list) -> argparse.Namespace:
    parser = argparse.ArgumentParser(prog="fit_hero_rig (bpy)")
    parser.add_argument("--input", required=True, help="the mesh to fit")
    parser.add_argument("--reference", required=True,
                        help="the glb whose authoring frame to match")
    parser.add_argument("--output", default="",
                        help="write the normalised mesh here (optional)")
    parser.add_argument("--floor", type=float, default=None,
                        help="authoring-space height the model's lowest point "
                             "is placed at; defaults to the reference's, "
                             "which is only right if the reference's bounding "
                             "box floor is where its FEET are")
    return parser.parse_args(argv)


def main() -> int:
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    args = parse_args(argv)

    table = reference_table()
    reference = load_points(args.reference)

    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.ops.import_scene.gltf(filepath=args.input)
    raw = mesh_points()
    points, (flip, scale, offset, yaw, centre) = normalise(
        raw, reference, args.floor)

    fitted: dict = {}
    fitted.update(fit_spine(points, table))
    fitted.update(fit_limbs(points, table))
    fitted.update(fit_gills(points, table))
    fitted, disagreement = mirror_pairs(fitted)
    broken = check_protrusions(fitted, points)

    bones = []
    for name, parent, head, tail in table:
        got = fitted.get(name)
        if got is None:
            bones.append([name, parent, list(head), list(tail)])
            continue
        bones.append([name, got[0],
                      [round(float(v), 4) for v in got[1]],
                      [round(float(v), 4) for v in got[2]]])

    if args.output:
        # THE EXPORT MUST REPLAY THE EXACT TRANSFORM THE TABLE WAS FITTED IN,
        # and building it piecemeal from scale and location got that wrong:
        # the yaw was applied to the points the bones were fitted to but not
        # to the mesh that was written, so the exported model lay diagonally
        # across a skeleton that ran straight down its axis. One matrix,
        # composed in the same order normalise() works in, cannot drift from
        # it that way.
        from mathutils import Matrix  # type: ignore
        recentre = Matrix.Translation((-centre[0], -centre[1], 0.0))
        spin = Matrix.Rotation(-yaw, 4, "Z")
        mirror = Matrix.Diagonal((-1.0, -1.0, 1.0, 1.0)) if flip \
            else Matrix.Identity(4)
        resize = Matrix.Diagonal((scale, scale, scale, 1.0))
        shift = Matrix.Translation(offset)
        frame = shift @ resize @ mirror @ spin @ recentre

        for obj in bpy.data.objects:
            if obj.type == "MESH":
                obj.matrix_world = frame @ obj.matrix_world
        bpy.ops.object.select_all(action="DESELECT")
        bpy.ops.export_scene.gltf(
            filepath=args.output, export_format="GLB", export_apply=True,
            export_normals=True, export_materials="EXPORT",
            export_image_format="AUTO", export_jpeg_quality=92,
            export_animations=False, export_skins=False, export_yup=True)

    print("FITRIG " + json.dumps({
        "input": args.input,
        "reference": args.reference,
        "output": args.output,
        "normalisation": {"flippedHeadToPlusY": flip, "scale": scale,
                          "yawCorrectionDeg": round(math.degrees(yaw), 3),
                          "offset": [round(v, 4) for v in offset]},
        "targetBounds": {"min": [round(float(v), 4) for v in points.min(axis=0)],
                         "max": [round(float(v), 4) for v in points.max(axis=0)]},
        "referenceBounds": {
            "min": [round(float(v), 4) for v in reference.min(axis=0)],
            "max": [round(float(v), 4) for v in reference.max(axis=0)]},
        "bones": bones,
        "mirrorDisagreement": disagreement,
        "protrusionFailures": broken,
        "blender": bpy.app.version_string,
    }))
    # A lopsided fit is a FAILED fit, not a warning. Exiting non-zero stops
    # the caller binding weights to a skeleton whose left and right disagree.
    return 1 if broken else 0


if __name__ == "__main__":
    code = main()
    if code != 0:
        sys.exit(code)
